#include "generic.h"
#include "battlesystem.h"
#include "audio.h"

#define DEFAULT_MUSIC MUS_battle

BattleEncounter battleEncounterData[256] = {
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    1 */	{ { 11 }, DEFAULT_MUSIC, 0 },
/*    2 */	{ { 11, 11 }, DEFAULT_MUSIC, 0 },
/*    3 */	{ { 12 }, DEFAULT_MUSIC, 0 },
/*    4 */	{ { 12, 12 }, DEFAULT_MUSIC, 0 },
/*    5 */	{ { 13, 48, 49 }, MUS_navybattle, 0 },
/*    6 */	{ { 14 }, DEFAULT_MUSIC, 0 },
/*    7 */	{ { 14, 14 }, DEFAULT_MUSIC, 0 },
/*    8 */	{ { 15 }, MUS_boss1, 1 },
/*    9 */	{ { 16 }, MUS_lbpre, 0 },
/*   10 */	{ { 17 }, MUS_lbpre, 0 },
/*   11 */	{ { 18, 18 }, DEFAULT_MUSIC, 0 },
/*   12 */	{ { 19 }, DEFAULT_MUSIC, 0 },
/*   13 */	{ { 20 }, DEFAULT_MUSIC, 0 },
/*   14 */	{ { 20, 20 }, DEFAULT_MUSIC, 0 },
/*   15 */	{ { 21 }, DEFAULT_MUSIC, 0 },
/*   16 */	{ { 22 }, DEFAULT_MUSIC, 0 },
/*   17 */	{ { 21, 22 }, DEFAULT_MUSIC, 0 },
/*   18 */	{ { 21, 22, 23 }, DEFAULT_MUSIC, 0 },
/*   19 */	{ { 21, 22, 23, 23 }, DEFAULT_MUSIC, 0 },
/*   20 */	{ { 24, 25, 26 }, DEFAULT_MUSIC, 0 },
/*   21 */	{ { 27, 37, 37 }, MUS_lbpre, 0 },
/*   22 */	{ { 28 }, MUS_lbpre, 0 },
/*   23 */	{ { 29, 14 }, DEFAULT_MUSIC, 0 },
/*   24 */	{ { 30 }, DEFAULT_MUSIC, 0 },
/*   25 */	{ { 30, 30 }, DEFAULT_MUSIC, 0 },
/*   26 */	{ { 31 }, DEFAULT_MUSIC, 0 },
/*   27 */	{ { 32 }, DEFAULT_MUSIC, 0 },
/*   28 */	{ { 33 }, MUS_boss2pre, 2 },
/*   29 */	{ { 34, 34 }, DEFAULT_MUSIC, 0 },
/*   30 */	{ { 34, 34, 34 }, DEFAULT_MUSIC, 0 },
/*   31 */	{ { 34, 34, 34, 34 }, DEFAULT_MUSIC, 0 },
/*   32 */	{ { 35, 34, 34, 34 }, MUS_scarybattle, 0 },
/*   33 */	{ { 34 }, DEFAULT_MUSIC, 0 },
/*   34 */	{ { 37, 37 }, DEFAULT_MUSIC, 0 },
/*   35 */	{ { 37, 37, 37 }, DEFAULT_MUSIC, 0 },
/*   36 */	{ { 38, 37, 37 }, DEFAULT_MUSIC, 0 },
/*   37 */	{ { 39 }, DEFAULT_MUSIC, 0 },
/*   38 */	{ { 39, 39 }, DEFAULT_MUSIC, 0 },
/*   39 */	{ { 39, 39, 39 }, DEFAULT_MUSIC, 0 },
/*   40 */	{ { 40, 70, 71 }, DEFAULT_MUSIC, 0 },
/*   41 */	{ { 41 }, MUS_battlerisk, 14 },
/*   42 */	{ { 42 }, DEFAULT_MUSIC, 0 },
/*   43 */	{ { 42, 42 }, DEFAULT_MUSIC, 0 },
/*   44 */	{ { 42, 42, 42 }, DEFAULT_MUSIC, 0 },
/*   45 */	{ { 43, 43, 43 }, DEFAULT_MUSIC, 0 },
/*   46 */	{ { 44, 44, 44 }, DEFAULT_MUSIC, 0 },
/*   47 */	{ { 45, 45, 45 }, DEFAULT_MUSIC, 0 },
/*   48 */	{ { 46 }, MUS_boss2, 3 },
/*   49 */	{ { 47 }, MUS_navybattle, 0 },
/*   50 */	{ { 50 }, DEFAULT_MUSIC, 0 },
/*   51 */	{ { 51 }, MUS_battlerisk, 3 },
/*   52 */	{ { 52 }, MUS_battleillus, 6 },
/*   53 */	{ { 53 }, MUS_battleillus, 6 },
/*   54 */	{ { 54 }, MUS_battleillus, 6 },
/*   55 */	{ { 55 }, MUS_battlegate, 7 },
/*   56 */	{ { 56, 57 }, DEFAULT_MUSIC, 0 },
/*   57 */	{ { 58, 59 }, DEFAULT_MUSIC, 0 },
/*   58 */	{ { 60 }, MUS_battle2, 0 },
/*   59 */	{ { 61 }, DEFAULT_MUSIC, 0 },
/*   60 */	{ { 61, 61 }, DEFAULT_MUSIC, 0 },
/*   61 */	{ { 61, 61, 61 }, DEFAULT_MUSIC, 0 },
/*   62 */	{ { 61, 61, 61, 61 }, DEFAULT_MUSIC, 0 },
/*   63 */	{ { 65, 62, 63 }, MUS_battlestrong, 12 },
/*   64 */	{ { 64 }, MUS_boss3, 12 },
/*   65 */	{ { 66 }, MUS_trance, 6 },
/*   66 */	{ { 67 }, MUS_trance, 6 },
/*   67 */	{ { 68 }, MUS_brilliant2, 9 },
/*   68 */	{ { 42, 42, 42, 42 }, DEFAULT_MUSIC, 0 },
/*   69 */	{ { 69 }, MUS_trance, 6 },
/*   70 */	{ { 28 }, MUS_lbpre, 0 },
/*   71 */	{ { 72 }, DEFAULT_MUSIC, 0 },
/*   72 */	{ { 73 }, MUS_battlepower, 13 },
/*   73 */	{ { 74, 75 }, DEFAULT_MUSIC, 0 },
/*   74 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   75 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   76 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   77 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   78 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   79 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   80 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   81 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   82 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   83 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   84 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   85 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   86 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   87 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   88 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   89 */	{ {  }, DEFAULT_MUSIC, 0 },
/*   90 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*    0 */	{ {  }, DEFAULT_MUSIC, 0 },
/*  191 */	{ { 191 }, MUS_lbpre, 4 },
/*  192 */	{ { 192 }, MUS_lbpre, 4 },
};
