CC=x86_64-w64-mingw32-gcc

C_SOURCES = $(wildcard *.c)
C_HEADERS = $(wildcard *.h)
OBJ = $(patsubst %.c,_obj/win/%.o,$(C_SOURCES))

rubixplore.exe: ${OBJ} _obj/win/resource.o
	$(CC) $^ -o $@ -lm -mwindows -lSDL2 -lSDL2_image -lSDL2_mixer -lzip -s

_obj/win/resource.o: resource.rc
	x86_64-w64-mingw32-windres $< -o $@

_obj/win/%.o: %.c $(C_HEADERS)
	$(CC) -c $< -o $@ -Wno-pointer-sign
